language: php
php:
    - 7.0

branches:
    only:
        - master

before_script:
    - composer install --prefer-source --dev
    - php bin/console doctrine:database:create -e=test
    - php bin/console doctrine:schema:update --force -e=test

script:
    - php bin/console server:run -e=test &
    - sleep 1
    - ./bin/behat --format=progress
    - ./bin/phpspec run --format=pretty
