standard:
    resource: '@CiTron/Controller/DefaultController.php'
    type: annotation
    prefix: /back

security:
    resource: '@CiTron/Controller/SecurityController.php'
    type: annotation
    prefix: /back/security

user:
    resource: '@CiTron/User/Controller'
    type: annotation
    prefix: /back

project:
    resource: '@CiTron/Project/Controller'
    type: annotation
    prefix: /back

login_check:
    path: /back/login
    methods: [POST]

logout:
    path: /back/logout
    methods: [GET]

front_js_404:
    path: /{anything}.js
    defaults: { _controller: 'CiTron:Default:notFound' }
    requirements:
        anything: .*

front:
    path: /{anything}
    defaults: { _controller: 'CiTron:Default:front' }
    methods: GET
    requirements:
        anything: .*
