standard:
    resource: '@CiTron/Controller/DefaultController.php'
    type: annotation
    prefix: /back

security:
    resource: '@CiTron/Controller/SecurityController.php'
    type: annotation
    prefix: /back/security

user:
    resource: '@CiTron/User/Controller'
    type: annotation
    prefix: /back

project:
    resource: '@CiTron/Project/Controller'
    type: annotation
    prefix: /back

login_check:
    path: /back/login
    methods: [POST]

logout:
    path: /back/logout
    methods: [GET]
