# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

imports:
    - { resource: services/api/listeners.yml }
    - { resource: services/user/listeners.yml }
    - { resource: services/project/services.yml }
    - { resource: services/server/server.yml }
