# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

imports:
    - { resource: services/api/listeners.yml }
    - { resource: services/user/listeners.yml }
    - { resource: services/server/factory.yml }
    - { resource: services/server/servers.yml }


services:
#    service_name:
#        class: CiTron\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
