front:
    resource: '@CiTron/Controller/DefaultController.php'
    type: annotation

user:
    resource: '@CiTron/User/Controller'
    type: annotation

login_check:
    path: /login
    methods: [POST]

logout:
    path: /logout
    methods: [GET]
