home_routes:
    prefix: /
    resource: routing/home.yml

users_routes:
    prefix: /secured/users
    resource: routing/users.yml

security_routes:
    prefix: /security
    resource: routing/security.yml
