# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        CiTron\User\Entity\User:
            algorithm:           sha512
            encode_as_base64:    true
            iterations:          162

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers

    providers:
        main:
            entity:
                class: User:User
                property: username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern:    ^/
            form_login:
                provider: main
                check_path: /login
                login_path: /login-status.json
                always_use_default_target_path: true
                default_target_path: /login-status.json
                failure_path: /login-status.json
                default_target_path: profile
                username_parameter: username
                password_parameter: password
                require_previous_session: false
            logout:
                path:   logout
                target: /logout-success.json
            anonymous: ~

    access_control:
        - { path: ^/secured, roles: ROLE_USER }
