
current_user_profile:
    path: /profile.json
    defaults: { _controller: 'CiTron:User/Profile:getUser' }
    methods: [GET]

user_profile:
    path: /profile/{slug}.json
    defaults: { _controller: 'CiTron:User/Profile:getUser' }
    methods: [GET]
